name: Deploy

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world from development!"

  staging:
    runs-on: ubuntu-latest
    needs: development
    environment: staging

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world from staging!"

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world from production!"
