name: Create deployments with GitHub App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "development"

      deployment_status:
        description: "Status of the deployment"
        required: true
        default: success
        type: choice
        options:
          - success
          - error
          - failure
          - inactive
          - in_progress
          - queued
          - pending

      environment_url:
        description: "URL of the environment"
        required: true
        default: https://example.com

      log_url:
        description: "URL of the deployment logs"
        required: true
        default: https://team-github.testoctopus.app

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create deployment
        id: create-deployment
        run: 'echo deploymentid=$(gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/deployments -F "ref=${{ github.event.pull_request.head.sha || github.sha }}" -F "description=Deployed by Octopus" -F "environment=${{ inputs.environment }}" -F "auto_merge=false" --jq ".id")  >> $GITHUB_OUTPUT'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Set deployment status
        run: 'gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/deployments/${{ steps.create-deployment.outputs.deploymentid }}/statuses -f "environment=${{ inputs.environment }}" -f "state=${{ inputs.deployment_status }}" -f "log_url=${{ inputs.log_url }}" -f "description=Deployment to environment ${{ steps.create-deployment.outputs.deploymentid }}." -f "environment_url=${{ inputs.environment_url }}" -F "auto_inactive=false"'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
